config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, only: [:index, :create, :new]
  resources :session, only: [:new, :create, :destroy]
  resources :schedules, only: [:index, :update, :edit]
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionHelper
  def authen
    redirect_to new_session_path if !user_signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authen, only: [:index]
  def index
  end

  def new
  end

  def create
      email = User.find_by(email:params[:email])
      password = params[:password]
      if (!email) && (password.length >= 6)
        User.create(name:params[:name], email:params[:email],
                    password:params[:password],
                    password_confirmation:params[:password_confirmation])
        flash[:alert] = "회원가입에 성공하셨습니다."
        redirect_to '/'
      else
        flash[:alert] = "이메일/비밀번호 입력을 다시 해주세요."
        redirect_to new_post_path
      end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authen
  def index
    @schedules = Schedule.all
  end

  def edit
    @schedule = Schedule.find_by(id:params[:id])
    flash[:alert] = @schedule.date
  end

  def update
    schedule = Schedule.find_by(id:params[:id])
    schedule.update(liveCoding:params[:liveCoding],
                    uniLion:params[:uniLion],
                    fLearning:params[:fLearning],
                    hackerThon:params[:hackerThon],
                    soloRun:params[:soloRun])
    redirect_to schedules_path,method:"get"
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  before_action :authen, only: [:destroy]

  def new
  end

  def create
    user = User.find_by(email:params[:email])
    if !!user && !!user.authenticate(params[:password])
      log_in(user)
      flash[:alert] = user.name+"님 안녕하세요."
      redirect_to '/'
    else
      flash[:alert] = "이메일/비밀번호 정보가 잘못 되었습니다."
      redirect_to new_session_path
    end
  end

  def destroy
    log_out
    flash[:alert] = "로그아웃에 성공하셨습니다."
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper


end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user = @current_user
    end
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/posts/index.erb
<div class="main">
  <h1>안녕하세요. 진도표 등록/조회 사이트입니다.</h1>
  <img src="https://scontent.cdninstagram.com/t51.2885-15/e35/16122989_1693589110655086_6307382425928335360_n.jpg?ig_cache_key=MTQzMTc0NjU3MzQ2MDgxNTE1MA%3D%3D.2" alt="">
</div>

app/views/posts/log_in.erb
<div class="log_in">
  <h2>로그인</h2>
  <input class = "btn" type="text" placeholder="이메일을 입력하시오"/>
  <input class = "btn" type="password" placeholder="비밀번호를 입력하시오"/>
  <input id = "submit" class = "btn" type="submit"/>
</div>

app/views/posts/new.erb

<%= form_tag posts_path, class:"sign_up" do %>
  <h1 id ="sign_up">회원가입</h1>
  <div class="detail">
    <p>이름</p>
    <input class = "btn" type="text" name="name">
  </div>
  <br/>
  <div class="detail">
    <p>이메일</p>
  <input class = "btn" type="email" name="email">
  </div>
  <br/>
  <div class="detail">
    <p>비밀번호</p>
  <input class = "btn" type="password" name="password" placeholder="6자이상 입력">
  </div>
  <br/>
  <div class="detail">
    <p>비밀번호 확인</p>
  <input class = "btn" type="password" name="password_confirmation" placeholder="6자이상 입력">
  </div>
  <br/>
  <input id = "submit" class = "btn" type="submit" value="입력완료">
<% end %>

app/views/schedules/edit.erb

<table class="table">
  <thead>
    <tr>
      <th>생활코딩</th>
      <th>멋사중앙</th>
      <th>플러닝+</th>
      <th>해커톤+</th>
      <th>솔로러닝</th>
    </tr>
  </thead>
  <tbody>
    <div = "td_control">
      <tr>
          <th scope="row"><%= @schedule.liveCoding %></th>
          <td><%= @schedule.uniLion %></td>
          <td><%= @schedule.fLearning %></td>
          <td><%= @schedule.hackerThon %></td>
          <td><%= @schedule.soloRun %></td>
      </tr>
    </div>
  </tbody>
</table>
<%= form_tag schedule_path(@schedule.id), method:"patch" do %>
  <div class = "ddd" >
    <input style = "width:15%;"class = "form-control" type="text" name="liveCoding" value="">
    <input style = "width:15%;"class = "form-control" type="text" name="uniLion" value="">
    <input style = "width:15%;"class = "form-control" type="text" name="fLearning" value="">
    <input style = "width:15%;"class = "form-control" type="text" name="hackerThon" value="">
    <input style = "width:15%;"class = "form-control" type="text" name="soloRun" value="">
  </div>
  <div id = "submit_edit" class = "mt-5">
    <input style = "width:30%;" class = "form-control mt-5" type="submit" value="작성완료">
  </div>
<% end %>

app/views/schedules/index.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>날짜</th>
        <th>생활코딩</th>
        <th>유니라이온</th>
        <th>Flearning</th>
        <th>해커톤</th>
        <th>solo_run</th>
      </tr>
    </thead>
    <tbody>
      <% @schedules.each do |sche| %>
        <tr>
          <th scope="row"><%= link_to sche.date, edit_schedule_path(sche.id), method:"get" %></th>
          <% if sche.liveCoding == nil  %>
            <td colspan="5"><%= link_to "입력하러가기", edit_schedule_path(sche.id), method:"get" %></td>
          <% else %>
            <td><%= sche.liveCoding %></td>
            <td><%= sche.uniLion %></td>
            <td><%= sche.fLearning %></td>
            <td><%= sche.hackerThon %></td>
            <td><%= sche.soloRun %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/session/new.erb
<%= form_tag session_index_path, method:"post", class:"log_in" do%>
  <h2>로그인</h2>
  <input class = "btn" type="email" name = "email" placeholder="이메일을 입력하시오"/>
  <input class = "btn" type="password" name = "password" placeholder="비밀번호를 입력하시오"/>
  <input id = "submit" class = "btn" type="submit"/>
<% end %>